'use client';

import { useRef } from 'react';
import { FileText, X } from 'lucide-react';

interface TextInputProps {
  value: string;
  onChange: (value: string) => void;
  disabled?: boolean;
}

const MAX_CHARS = 10000;

export default function TextInput({ value, onChange, disabled = false }: TextInputProps) {
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  const charCount = value.length;
  const percentage = (charCount / MAX_CHARS) * 100;
  const isNearLimit = percentage > 80;
  const isAtLimit = percentage >= 100;

  const handleClear = () => {
    onChange('');
    textareaRef.current?.focus();
  };

  const handlePaste = async () => {
    try {
      const text = await navigator.clipboard.readText();
      onChange(text.slice(0, MAX_CHARS));
    } catch {
      // Clipboard access denied, user can paste manually
    }
  };

  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className="flex items-center justify-between mb-2">
        <div className="flex items-center gap-2">
          <FileText className="w-4 h-4 text-violet-400" />
          <span className="text-sm font-medium text-gray-300">Input Text</span>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={handlePaste}
            disabled={disabled}
            className="text-xs text-violet-400 hover:text-violet-300 disabled:opacity-40 transition-colors px-2 py-1 rounded border border-violet-800 hover:border-violet-600"
          >
            Paste
          </button>
          {value && (
            <button
              onClick={handleClear}
              disabled={disabled}
              className="text-gray-500 hover:text-gray-300 disabled:opacity-40 transition-colors"
              title="Clear text"
            >
              <X className="w-4 h-4" />
            </button>
          )}
        </div>
      </div>

      {/* Textarea */}
      <div className="relative flex-1">
        <textarea
          ref={textareaRef}
          value={value}
          onChange={(e) => onChange(e.target.value.slice(0, MAX_CHARS))}
          disabled={disabled}
          placeholder="Paste your AI-generated text here...

Examples:
• Blog post content generated by ChatGPT
• Product descriptions written by AI
• Social media captions from AI tools
• Any text you want to make sound more human

The tool will analyze AI patterns and transform your text to sound authentically human."
          className="w-full h-full min-h-[280px] bg-gray-900/60 border border-gray-700 rounded-xl p-4 text-gray-200 placeholder-gray-600 resize-none focus:outline-none focus:border-violet-500 focus:ring-1 focus:ring-violet-500/30 transition-all text-sm leading-relaxed disabled:opacity-50 disabled:cursor-not-allowed"
        />
        {disabled && (
          <div className="absolute inset-0 flex items-center justify-center bg-gray-900/20 rounded-xl">
            <div className="flex items-center gap-2 text-gray-400">
              <div className="w-4 h-4 border-2 border-violet-400 border-t-transparent rounded-full animate-spin" />
              <span className="text-sm">Processing...</span>
            </div>
          </div>
        )}
      </div>

      {/* Character count */}
      <div className="flex items-center justify-between mt-2">
        <div className="flex-1 mr-4">
          <div className="h-1 bg-gray-800 rounded-full overflow-hidden">
            <div
              className={`h-full rounded-full transition-all duration-300 ${
                isAtLimit
                  ? 'bg-red-500'
                  : isNearLimit
                  ? 'bg-yellow-500'
                  : 'bg-violet-500'
              }`}
              style={{ width: `${Math.min(percentage, 100)}%` }}
            />
          </div>
        </div>
        <span
          className={`text-xs tabular-nums transition-colors ${
            isAtLimit
              ? 'text-red-400'
              : isNearLimit
              ? 'text-yellow-400'
              : 'text-gray-500'
          }`}
        >
          {charCount.toLocaleString()} / {MAX_CHARS.toLocaleString()}
        </span>
      </div>
    </div>
  );
}
